Ajout de la connexion à Amazon ECR et push Docker

diff --git a/.github/workflows/security-pipeline.yml b/.github/workflows/security-pipeline.yml
--- a/.github/workflows/security-pipeline.yml
+++ b/.github/workflows/security-pipeline.yml
@@ -114,29 +114,32 @@ jobs:
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
 
         # Construction de l’image Docker
-name: Security & Deployment Pipeline
+  name: Security & Deployment Pipeline
 
-on: 
-  push:
-    branches:
-      - main
+  on:
+    push:
+      branches:
+        - main
 
-jobs:
-  security_scan:
-    name: Security Scan
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  jobs:
+    build_and_scan:
+      name: Docker-AWS
+      runs-on: ubuntu-latest
+      needs: security_scan
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@master
 
-  build_and_scan:
-    name: Build & Scan Docker Image
-    runs-on: ubuntu-latest
-    needs: security_scan
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      # Assurer que AWS CLI est installé
+        - name: Install AWS CLI
+          run: |
+            if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found. Installing..."
+            sudo apt update && sudo apt install -y awscli
+          fi
+          aws --version
 
+      # Connexion à Amazon ECR
       - name: Log in to Amazon ECR
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -148,18 +151,3 @@ jobs:
           aws configure set region $AWS_REGION
           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
 
-      - name: Build Docker Image
-        run: docker build -t my-app:latest .
-
-      - name: Scan Docker Image with Trivy
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: 'my-app:latest'
-          exit-code: 1
-          ignore-unfixed: true
-
-      - name: Push Docker Image to ECR
-        run: |
-          docker tag my-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/my-app:latest
-          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/my-app:latest
- 
