Correction YAML indentation

diff --git a/.github/workflows/security-pipeline.yml b/.github/workflows/security-pipeline.yml
--- a/.github/workflows/security-pipeline.yml
+++ b/.github/workflows/security-pipeline.yml
@@ -88,29 +88,29 @@ jobs:
     needs: security_scan
 
     steps:
-        - name: Checkout code
-          uses: actions/checkout@master
+      - name: Checkout code
+        uses: actions/checkout@master
 
         # Assurer que AWS CLI est installé
-        - name: Install AWS CLI
-          run: |
-            if ! command -v aws &> /dev/null; then
-              echo "AWS CLI not found. Installing..."
-              sudo apt update && sudo apt install -y awscli
-            fi
-            aws --version
+      - name: Install AWS CLI
+        run: |
+          if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found. Installing..."
+            sudo apt update && sudo apt install -y awscli
+          fi
+          aws --version
 
         # Connexion à Amazon ECR
-        - name: Log in to Amazon ECR
-          env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_REGION: ca-central-1
-          run: |
-            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-            aws configure set region $AWS_REGION
-            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
+      - name: Log in to Amazon ECR
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ca-central-1
+        run: |
+          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+          aws configure set region $AWS_REGION
+          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
 
         # Construction de l’image Docker
   name: Security & Deployment Pipeline
@@ -125,28 +125,29 @@ jobs:
       name: Docker-AWS
       runs-on: ubuntu-latest
       needs: security_scan
+
       steps:
-      - name: Checkout code
-        uses: actions/checkout@master
+        - name: Checkout code
+          uses: actions/checkout@master
 
       # Assurer que AWS CLI est installé
-      - name: Install AWS CLI
-        run: |
-          if ! command -v aws &> /dev/null; then
-          echo "AWS CLI not found. Installing..."
-          sudo apt update && sudo apt install -y awscli
-        fi
-        aws --version
+        - name: Install AWS CLI
+          run: |
+            if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found. Installing..."
+            sudo apt update && sudo apt install -y awscli
+          fi
+          aws --version
 
       # Connexion à Amazon ECR
-      - name: Log in to Amazon ECR
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: us-east-1
-        run: |
-          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-          aws configure set region $AWS_REGION
-          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
+        - name: Log in to Amazon ECR
+          env:
+            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            AWS_REGION: us-east-1
+          run: |
+            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+            aws configure set region $AWS_REGION
+            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
 
